#!/usr/bin/env python

from sys import argv, exit
import os
import numpy as np

# ---------------------------------------------------------------------------
# Search limits (edit here if needed)
# MAX_ATOMS  : stop generating larger supercells once the bilayer exceeds
#              this total atom count (both layers combined)
# MAX_SC     : hard cap on (m, n) index as a safety guard
# STRAIN_SHOW: only show solutions with strain <= this value in the table
# ---------------------------------------------------------------------------
MAX_ATOMS   = 1000
MAX_SC      = 50
STRAIN_SHOW = 5.0   # percent


def usage():
    text = """
Usage: vaspTwist.py <input>

Generate twisted bilayer POSCAR files from a 2D monolayer POSCAR.

The script automatically:
  1. Searches all (m, n) integer pairs until the supercell exceeds
     {max_atoms} atoms (both layers combined).
  2. Computes the exact twist angle and strain for each pair.
  3. Shows a table of solutions with strain <= {strain_show}%.
  4. Asks which angle(s) to build.
  5. Writes one POSCAR per chosen angle (AA stacking, no in-plane shift).

Strain definition:
  For each (m, n), independent supercells are built from the original
  (bottom) and rotated (top) lattices.  Strain = max relative mismatch
  across supercell vector lengths and internal angle between the two cells.

This script was developed by Thanasee Thanasarnsurapong.
""".format(max_atoms=MAX_ATOMS, strain_show=STRAIN_SHOW)
    print(text)
    exit(0)

# ---------------------------------------------------------------------------
# I/O
# ---------------------------------------------------------------------------

def read_POSCAR(filepath):

    if not os.path.exists(filepath):
        print(f"ERROR!\nFile: {filepath} does not exist.")
        exit(1)

    with open(filepath, 'r') as f:
        lines = f.readlines()

    if len(lines[1].split()) == 1:
        raw_scale = float(lines[1])
        raw_lat   = np.array([[float(x) for x in line.split()]
                               for line in lines[2:5]])
        if raw_scale < 0:
            volume = abs(np.linalg.det(raw_lat))
            scale  = np.cbrt(abs(raw_scale) / volume)
        elif raw_scale == 0:
            print("ERROR! Scaling factor must not be zero.")
            exit(1)
        else:
            scale = raw_scale
        lattice = raw_lat * scale
    elif len(lines[1].split()) == 3:
        scale   = np.array(list(map(float, lines[1].split())))
        lattice = np.array([[float(x) * scale[i] for i, x in enumerate(line.split())]
                             for line in lines[2:5]])
    else:
        print("ERROR! Scaling factor must be 1 or 3 components.")
        exit(1)

    elements  = []
    is_number = lines[5].split()[0].isdecimal()
    if is_number:
        for i in range(len(lines[5].split())):
            while True:
                name = input(f"Enter the name of species No. {i+1:>3}: ").strip()
                if name.isalpha():
                    break
                print("Species name must be alphabetic only.")
            elements.append(name)
        atom_counts = [int(x) for x in lines[5].split()]
        sel_dyn     = lines[6].lower().startswith('s')
        pos_start   = 8 if sel_dyn else 7
    else:
        for name in lines[5].split():
            elements.append(name.split('/')[0].split('_')[0])
        atom_counts = [int(x) for x in lines[6].split()]
        sel_dyn     = lines[7].lower().startswith('s')
        pos_start   = 9 if sel_dyn else 8

    total    = sum(atom_counts)
    pos_stop = pos_start + total
    positions = np.array([[float(x) for x in lines[i].split()[:3]]
                           for i in range(pos_start, pos_stop)])
    species  = [el for el, cnt in zip(elements, atom_counts)
                for _ in range(cnt)]

    flags = None
    if sel_dyn:
        flags = np.array([[x for x in lines[i].split()[3:6]]
                           for i in range(pos_start, pos_stop)])

    is_direct = lines[pos_start - 1].strip().lower().startswith('d')
    if is_direct:
        pos_direct = positions % 1.0
        pos_cart   = direct_to_cart(lattice, pos_direct)
    else:
        pos_cart   = positions * scale
        pos_direct = cart_to_direct(lattice, pos_cart)

    return {"lattice":    lattice,
            "elements":   elements,
            "counts":     atom_counts,
            "total":      total,
            "pos_cart":   pos_cart,
            "pos_direct": pos_direct,
            "species":    species,
            "sel_dyn":    sel_dyn,
            "flags":      flags}


def write_POSCAR(filepath, lattice, elements, counts, pos_direct,
                 sel_dyn, flags, labels):

    with open(filepath, 'w') as o:
        o.write("Generated by vaspTwist.py\n")
        o.write(f"   {1.0:.14f}\n")
        for row in lattice:
            o.write(f"   {row[0]:20.16f}  {row[1]:20.16f}  {row[2]:20.16f}\n")
        o.write("   " + "    ".join(elements) + " \n")
        o.write("     " + "    ".join(map(str, counts)) + "\n")
        if sel_dyn:
            o.write("Selective dynamics\n")
        o.write("Direct\n")
        if sel_dyn:
            for p, fl, lb in zip(pos_direct, flags, labels):
                o.write(f"{p[0]:20.16f}{p[1]:20.16f}{p[2]:20.16f}"
                        f"   {fl[0]}   {fl[1]}   {fl[2]}   {lb:>6s}\n")
        else:
            for p, lb in zip(pos_direct, labels):
                o.write(f"{p[0]:20.16f}{p[1]:20.16f}{p[2]:20.16f}"
                        f"   {lb:>6s}\n")

# ---------------------------------------------------------------------------
# Coordinate transforms
# ---------------------------------------------------------------------------

def direct_to_cart(lattice, pos_direct):
    return np.dot(pos_direct % 1.0, lattice)

def cart_to_direct(lattice, pos_cart):
    return np.dot(pos_cart, np.linalg.inv(lattice)) % 1.0

# ---------------------------------------------------------------------------
# Rotation matrix around z-axis (Rodrigues' formula with u = [0, 0, 1])
#
# Rodrigues' rotation formula for unit axis u and angle theta:
#   R = cos(theta)*I + sin(theta)*(u x) + (1-cos(theta))*(u⊗u)
#
# For u = z = [0, 0, 1]:
#   u x I  = [[0,-1,0],[1,0,0],[0,0,0]]   (cross-product matrix)
#   u⊗u    = [[0,0,0],[0,0,0],[0,0,1]]
#
# This simplifies to the standard 2D rotation matrix with z unchanged:
#   R = [[ cos, -sin, 0 ],
#        [ sin,  cos, 0 ],
#        [  0,    0,  1 ]]
# ---------------------------------------------------------------------------

def rotation_matrix(angle_deg):
    """
    3x3 rotation matrix around the z-axis by angle_deg degrees.
    Derived from Rodrigues' formula with u = [0, 0, 1].
    """
    u      = np.array([0., 0., 1.])
    theta  = np.radians(angle_deg)
    sin    = np.sin(theta)
    cos    = np.cos(theta)
    rotate = (cos * np.eye(3)
              + sin * np.cross(np.eye(3), u)
              + (1 - cos) * np.outer(u, u))
    return rotate

# ---------------------------------------------------------------------------
# Expansion matrix validation and replicas extraction
# ---------------------------------------------------------------------------

def make_expansion_matrix(M2):
    """
    Convert a 2x2 in-plane supercell matrix M2 into a 3x3 expansion matrix
    and extract the number of replicas (= determinant).

    The z-direction is left as 1 (vacuum slab — never replicated in z).

    Applies the same validity checks as input_expansion():
      - determinant must be positive
      - determinant must be an integer (within 1e-6 tolerance)
    """
    expansion_matrix = np.eye(3, dtype=float)
    expansion_matrix[:2, :2] = M2.astype(float)

    det     = np.linalg.det(expansion_matrix)
    det_int = int(round(det))

    if det <= 1e-10:
        raise ValueError(
            f"Invalid expansion matrix: determinant = {det:.6f} "
            f"(must be a positive integer).")
    if abs(det - det_int) >= 1e-6 or det_int <= 0:
        raise ValueError(
            f"Invalid expansion matrix: determinant = {det:.6f} "
            f"is not a positive integer.")

    return expansion_matrix, det_int

# ---------------------------------------------------------------------------
# Build supercell (provided function — unchanged)
# ---------------------------------------------------------------------------

def build_supercell(expansion_matrix,
                    replicas,
                    lattice_matrix,
                    atom_counts,
                    total_atoms,
                    positions_cartesian,
                    species,
                    selective_dynamics,
                    flags):

    new_lattice_matrix = np.dot(expansion_matrix, lattice_matrix)

    corners = np.array([[i, j, k]
                        for i in range(2) for j in range(2) for k in range(2)])
    corner_transformed = np.dot(corners, expansion_matrix)
    min_points = np.min(corner_transformed, axis=0).astype(int)
    max_points = np.max(corner_transformed, axis=0).astype(int) + 1
    all_points = np.array([[i, j, k] for i in range(min_points[0], max_points[0])
                                     for j in range(min_points[1], max_points[1])
                                     for k in range(min_points[2], max_points[2])])
    adj = np.round(np.linalg.inv(expansion_matrix) * replicas).astype(int)
    frac_points = np.dot(all_points, adj)
    mask = (np.all(frac_points >= 0, axis=1) &
            np.all(frac_points <  replicas, axis=1))
    grid_points = all_points[mask]

    if len(grid_points) != replicas:
        print(f"WARNING: Expected {replicas} grid points but found {len(grid_points)}. "
              "Check your expansion matrix.")

    grid_cartesian = np.dot(grid_points, lattice_matrix)
    new_positions_cartesian = (
        positions_cartesian[:, np.newaxis, :] +
        grid_cartesian[np.newaxis, :, :]
    ).reshape(-1, 3)
    new_species = np.repeat(species, len(grid_points)).tolist()

    new_flags = None
    if selective_dynamics:
        new_flags = np.tile(flags[:, np.newaxis, :],
                            (1, len(grid_points), 1)).reshape(-1, 3)

    new_atom_counts = [count * replicas for count in atom_counts]
    new_total_atoms = total_atoms * replicas

    new_positions_direct = cart_to_direct(new_lattice_matrix, new_positions_cartesian)

    return {"lattice_matrix":      new_lattice_matrix,
            "atom_counts":         new_atom_counts,
            "total_atoms":         new_total_atoms,
            "positions_direct":    new_positions_direct,
            "positions_cartesian": new_positions_cartesian,
            "species":             new_species,
            "flags":               new_flags}

# ---------------------------------------------------------------------------
# Atom ordering / label helpers
# ---------------------------------------------------------------------------

def check_elements(elements):
    unique = list(dict.fromkeys(elements))
    if len(elements) == len(unique):
        return None
    print("\nFound duplicated elements in POSCAR!")
    print("Unique elements: [" + " ".join(unique) + "]")
    while True:
        order = input("Enter desired element order (space-separated): ").split()
        if not order:
            order = unique.copy()
        if len(order) == len(unique) and set(order) == set(unique):
            return order
        print("ERROR! Species do not match unique elements. Try again.")


def reorder_atoms(elements, counts, pos_cart, pos_direct,
                  species, sel_dyn, flags, sort_order):
    ec, ed, esp, ef = {}, {}, {}, {}
    idx = 0
    for el, cnt in zip(elements, counts):
        ec .setdefault(el, []).extend(pos_cart  [idx:idx+cnt].tolist())
        ed .setdefault(el, []).extend(pos_direct[idx:idx+cnt].tolist())
        esp.setdefault(el, []).extend(species   [idx:idx+cnt])
        if sel_dyn:
            ef.setdefault(el, []).extend(flags  [idx:idx+cnt].tolist())
        idx += cnt

    nc, nd, ns, nf, new_counts = [], [], [], [], []
    for el in sort_order:
        nc.extend(ec [el]);  nd.extend(ed [el])
        ns.extend(esp[el]);  new_counts.append(len(ed[el]))
        if sel_dyn:
            nf.extend(ef[el])

    return {"elements":   sort_order,
            "counts":     new_counts,
            "pos_cart":   np.array(nc, dtype=float),
            "pos_direct": np.array(nd, dtype=float),
            "species":    ns,
            "flags":      np.array(nf) if sel_dyn else None}


def make_labels(elements, counts):
    digits = len(str(max(counts))) + 1
    return [f"{el}{str(i).zfill(digits)}"
            for el, cnt in zip(elements, counts)
            for i in range(1, cnt + 1)]

# ---------------------------------------------------------------------------
# Sheet centering (z at fractional 0.5)
# ---------------------------------------------------------------------------

def unwrap(pos_direct):
    ref   = pos_direct[0].copy()
    delta = pos_direct - ref
    delta -= np.round(delta)
    return ref, ref + delta

def center_sheet(pos_direct):
    ref, unwrapped = unwrap(pos_direct)
    center = np.mean(unwrapped, axis=0)
    new    = unwrapped.copy()
    new[:, :2] = unwrapped[:, :2] - ref[:2]
    new[:,  2] = unwrapped[:,  2] - center[2] + 0.5
    return new % 1.0

# ---------------------------------------------------------------------------
# GCD
# ---------------------------------------------------------------------------

def gcd(a, b):
    a, b = abs(int(round(a))), abs(int(round(b)))
    while b:
        a, b = b, a % b
    return a

# ---------------------------------------------------------------------------
# Partner-vector search
#
# Given t1 = m*a1 + n*a2, we need a partner t2 = p*a1 + q*a2 such that
# (t1, t2) form a valid 2D supercell.  t2 must:
#   1. Be a real lattice vector (integer p, q combination of a1, a2)
#   2. Not be collinear with t1  (would give zero-area cell)
#   3. Have length as close to |t1| as possible  (minimise cell distortion)
#
# Search radius derivation
# ------------------------
# We need to find t2 whose length is close to |t1|.
# The maximum length of t1 is:
#     |t1| <= |m|*|a1| + |n|*|a2| <= (|m|+|n|) * max(|a1|, |a2|)
#
# A lattice vector p*a1 + q*a2 of length L requires indices of at most:
#     max(|p|, |q|) <= L / min_proj
# where min_proj is the smallest projection of any basis vector onto any
# direction, i.e. the shortest distance between parallel lattice lines:
#     min_proj = area / max(|a1|, |a2|)   (= perpendicular height of cell)
#
# Combining: to reach length |t1|, we need at most
#     max(|p|, |q|) <= |t1| / min_proj
#                    = |t1| * max(|a1|,|a2|) / area
#                   <= (|m|+|n|) * max(|a1|,|a2|)^2 / area
#
# We define this as the radius, with a small integer buffer (+2) to guard
# against floating-point rounding near the boundary.
# ---------------------------------------------------------------------------

def partner_search_radius(m, n, lat2d):
    """
    Compute the minimum safe integer search radius for find_partner.

    The radius guarantees that no lattice vector of length <= |t1| is missed.
    Derived from the lattice geometry rather than a fixed heuristic.

    Parameters
    ----------
    m, n  : int   — supercell indices defining t1 = m*a1 + n*a2
    lat2d : (2,2) — in-plane lattice matrix, rows = a1, a2

    Returns
    -------
    radius : int
    """
    a1, a2   = lat2d[0], lat2d[1]
    len_a1   = np.linalg.norm(a1)
    len_a2   = np.linalg.norm(a2)
    len_max  = max(len_a1, len_a2)
    area     = abs(np.cross(a1, a2))

    # Upper bound on |t1|
    len_t1_max = (abs(m) + abs(n)) * len_max

    # Minimum perpendicular height of the primitive cell
    # (shortest distance between parallel rows of lattice points)
    min_proj = area / len_max   # = min(|a1|*sin, |a2|*sin) of cell angle

    # Maximum index needed to reach a vector of length len_t1_max
    # Guard against degenerate (zero-area) cells
    if min_proj < 1e-10 or len_max < 1e-10:
        return abs(m) + abs(n) + 2

    radius = int(np.ceil(len_t1_max / min_proj)) + 2

    return radius


def find_partner(m, n, lat2d):
    """
    For t1 = m*a1 + n*a2, find the lattice vector t2 = p*a1 + q*a2 that:
      - is NOT collinear with t1  (non-zero cell area)
      - has length closest to |t1|  (minimise supercell distortion)

    The search radius is derived from the lattice geometry via
    partner_search_radius(), guaranteeing no candidate is missed.

    Returns (t1, t2, N) where N = |area(t1,t2)| / area_prim  (replicas).
    """
    a1, a2 = lat2d[0], lat2d[1]
    t1     = m * a1 + n * a2
    lt1    = np.linalg.norm(t1)
    area_p = abs(np.cross(a1, a2))
    radius = partner_search_radius(m, n, lat2d)

    best_diff = np.inf
    t2_best   = None
    N_best    = 0

    for p in range(-radius, radius + 1):
        for q in range(-radius, radius + 1):
            if p == 0 and q == 0:
                continue
            cand  = p * a1 + q * a2
            lc    = np.linalg.norm(cand)
            if lc < 1e-10:
                continue
            # Reject collinear vectors (cross product ≈ 0)
            sin_a = abs(np.cross(t1, cand)) / (lt1 * lc)
            if sin_a < 1e-6:
                continue
            diff = abs(lc - lt1) / lt1
            if diff < best_diff:
                best_diff = diff
                t2_best   = cand
                N_best    = max(1, round(abs(np.cross(t1, cand)) / area_p))

    return t1, t2_best, N_best

# ---------------------------------------------------------------------------
# Strain between bottom and top supercells
# ---------------------------------------------------------------------------

def vec_angle_deg(v1, v2):
    cos = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-30)
    return np.degrees(np.arccos(np.clip(cos, -1, 1)))


def calc_strain(t1_bot, t2_bot, t1_top, t2_top):
    """Returns (strain_pct, dL1_pct, dL2_pct, dAng_pct)."""
    l1b, l2b = np.linalg.norm(t1_bot), np.linalg.norm(t2_bot)
    l1t, l2t = np.linalg.norm(t1_top), np.linalg.norm(t2_top)

    if min(l1b, l2b, l1t, l2t) < 1e-10:
        return 100., 100., 100., 100.

    dL1  = abs(l1b - l1t) / max(l1b, l1t) * 100.
    dL2  = abs(l2b - l2t) / max(l2b, l2t) * 100.
    dAng = abs(vec_angle_deg(t1_bot, t2_bot) -
               vec_angle_deg(t1_top, t2_top)) / 180. * 100.

    return max(dL1, dL2, dAng), dL1, dL2, dAng

# ---------------------------------------------------------------------------
# Automatic enumeration of commensurate angles
# ---------------------------------------------------------------------------

def enumerate_twist_angles(lattice, n_prim):
    """
    Find all commensurate twist angles whose bilayer fits within MAX_ATOMS.
    Returns list of solution dicts sorted by angle.
    """
    lat2d     = lattice[:2, :2].copy()
    a1, a2    = lat2d[0], lat2d[1]
    area_prim = abs(np.cross(a1, a2))

    solutions   = []
    seen_angles = {}

    for m in range(1, MAX_SC + 1):
        if 2 * m * n_prim > MAX_ATOMS:
            break

        for n in range(0, m + 1):
            if gcd(m, n) != 1:
                continue

            t1_bot, t2_bot, N = find_partner(m, n, lat2d)
            if t2_bot is None or N == 0:
                continue
            if np.linalg.norm(t2_bot) < 1e-10:
                continue

            total_atoms = 2 * N * n_prim
            if total_atoms > MAX_ATOMS:
                continue

            angle = vec_angle_deg(t1_bot, t2_bot)
            if angle < 1e-4 or angle > 179.9999:
                continue

            R         = rotation_matrix(angle)
            lat2d_top = (R[:2, :2] @ lat2d.T).T

            t1_top, t2_top, _ = find_partner(m, n, lat2d_top)
            if t2_top is None:
                continue

            strain, dL1, dL2, dAng = calc_strain(
                t1_bot, t2_bot, t1_top, t2_top)

            sc_a       = 0.5 * (t1_bot + t1_top)
            sc_b       = 0.5 * (t2_bot + t2_top)
            area_sc    = abs(np.cross(sc_a, sc_b))
            size_ratio = area_sc / area_prim

            sc_lat = np.zeros((3, 3))
            sc_lat[0, :2] = sc_a
            sc_lat[1, :2] = sc_b
            sc_lat[2]     = lattice[2]

            inv_bot = np.linalg.inv(lat2d)
            inv_top = np.linalg.inv(lat2d_top)
            M_bot   = np.array([np.round(t1_bot @ inv_bot).astype(int),
                                 np.round(t2_bot @ inv_bot).astype(int)])
            M_top   = np.array([np.round(t1_top @ inv_top).astype(int),
                                 np.round(t2_top @ inv_top).astype(int)])

            if np.linalg.det(M_bot) < 0.5 or np.linalg.det(M_top) < 0.5:
                continue

            angle_key = round(angle, 3)
            entry = {"angle_deg":   angle,
                     "m":           m,
                     "n":           n,
                     "N":           N,
                     "M_bot":       M_bot,
                     "M_top":       M_top,
                     "sc_lat":      sc_lat,
                     "strain_pct":  strain,
                     "dL1_pct":     dL1,
                     "dL2_pct":     dL2,
                     "dAng_pct":    dAng,
                     "size_ratio":  size_ratio,
                     "total_atoms": total_atoms}

            if angle_key in seen_angles:
                idx = seen_angles[angle_key]
                if strain < solutions[idx]["strain_pct"]:
                    solutions[idx] = entry
            else:
                seen_angles[angle_key] = len(solutions)
                solutions.append(entry)

    solutions.sort(key=lambda x: x["angle_deg"])
    return solutions

# ---------------------------------------------------------------------------
# Build twisted bilayer POSCAR using build_supercell
# ---------------------------------------------------------------------------

def build_twist_poscar(mono, sol, flip=False):
    """
    Build the twisted bilayer supercell in AA stacking.

    Steps:
      1. Center the monolayer sheet at z = 0.5.
      2. Convert M_bot -> (expansion_matrix, replicas) via make_expansion_matrix.
      3. Expand bottom layer with build_supercell.
      4. Rotate primitive lattice and positions around z by twist angle.
      5. Convert M_top -> (expansion_matrix, replicas) via make_expansion_matrix.
      6. Expand top layer with build_supercell.
      7. Shift top layer above bottom by interlayer gap.
      8. Wrap both layers into the shared supercell (sc_lat).
      9. Merge and sort elements.
    """
    lattice = mono["lattice"]
    angle   = sol["angle_deg"]
    M_bot   = sol["M_bot"]
    M_top   = sol["M_top"]
    sc_lat  = sol["sc_lat"]

    R = rotation_matrix(angle)

    # ---- Centred primitive positions ----
    prim_dir  = center_sheet(mono["pos_direct"])
    prim_cart = direct_to_cart(lattice, prim_dir)

    # ---- Bottom layer ----
    E_bot, replicas_bot = make_expansion_matrix(M_bot)
    bot = build_supercell(
              expansion_matrix    = E_bot,
              replicas            = replicas_bot,
              lattice_matrix      = lattice,
              atom_counts         = mono["counts"],
              total_atoms         = mono["total"],
              positions_cartesian = prim_cart,
              species             = mono["species"],
              selective_dynamics  = mono["sel_dyn"],
              flags               = mono["flags"])

    # ---- Top layer: rotate lattice and positions around z, then expand ----
    lat_top       = R @ lattice               # rotate all lattice vectors
    top_prim_cart = (R @ prim_cart.T).T       # rotate all atomic positions

    E_top, replicas_top = make_expansion_matrix(M_top)
    top = build_supercell(
              expansion_matrix    = E_top,
              replicas            = replicas_top,
              lattice_matrix      = lat_top,
              atom_counts         = mono["counts"],
              total_atoms         = mono["total"],
              positions_cartesian = top_prim_cart,
              species             = mono["species"],
              selective_dynamics  = mono["sel_dyn"],
              flags               = mono["flags"])

    # ---- Shift top layer above bottom layer ----
    thickness = np.max(prim_cart[:, 2]) - np.min(prim_cart[:, 2])
    gap       = max(3.0, thickness + 3.0)
    top["positions_cartesian"][:, 2] += gap

    if flip:
        zmax = np.max(top["positions_cartesian"][:, 2])
        zmin = np.min(top["positions_cartesian"][:, 2])
        top["positions_cartesian"][:, 2] = zmax + zmin - top["positions_cartesian"][:, 2]

    # ---- Wrap into shared supercell ----
    inv_sc  = np.linalg.inv(sc_lat)
    bot_dir = (bot["positions_cartesian"] @ inv_sc) % 1.0
    top_dir = (top["positions_cartesian"] @ inv_sc) % 1.0
    all_dir = np.vstack([bot_dir, top_dir])
    all_cart = all_dir @ sc_lat

    # ---- Merge elements and counts ----
    elements = mono["elements"] + mono["elements"]
    counts   = bot["atom_counts"] + top["atom_counts"]
    species  = bot["species"] + top["species"]

    sort_order = check_elements(elements)
    if sort_order is not None:
        mapped   = reorder_atoms(elements, counts, all_cart, all_dir,
                                 species, False, None, sort_order)
        elements = mapped["elements"]
        counts   = mapped["counts"]
        all_dir  = mapped["pos_direct"]

    return {"lattice":    sc_lat,
            "elements":   elements,
            "counts":     counts,
            "pos_direct": all_dir,
            "sel_dyn":    False,
            "flags":      None}

# ---------------------------------------------------------------------------
# Interactive prompts
# ---------------------------------------------------------------------------

def print_table(solutions):
    header = (f"  {'#':>4}  {'Angle (deg)':>12}  {'m':>4}  {'n':>4}  "
              f"{'N':>5}  {'Tot.atoms':>10}  "
              f"{'Strain(%)':>10}  "
              f"{'dL1(%)':>7}  {'dL2(%)':>7}  {'dAng(%)':>8}  "
              f"{'Size(x)':>8}")
    print(header)
    print("  " + "-" * (len(header) - 2))
    for i, sol in enumerate(solutions):
        print(f"  {i+1:>4}  {sol['angle_deg']:>12.5f}  "
              f"{sol['m']:>4}  {sol['n']:>4}  "
              f"{sol['N']:>5}  {sol['total_atoms']:>10}  "
              f"{sol['strain_pct']:>10.4f}  "
              f"{sol['dL1_pct']:>7.4f}  {sol['dL2_pct']:>7.4f}  "
              f"{sol['dAng_pct']:>8.4f}  "
              f"{sol['size_ratio']:>8.3f}")
    print()
    print("  Strain(%) = max(dL1, dL2, dAng) -- overall mismatch between layers")
    print("  dL1 / dL2 = relative length mismatch of supercell vectors 1 and 2")
    print("  dAng      = |angle_bot - angle_top| / 180 * 100")
    print()


def prompt_selection(solutions):
    while True:
        raw = input(
            "  Enter number(s) to build (e.g.  2  or  1 3 5  or  all): "
        ).strip().lower()

        if raw == "all":
            return list(solutions)
        if raw in ("", "none", "q", "quit"):
            return []

        tokens = raw.replace(",", " ").split()
        try:
            indices = [int(t) for t in tokens]
        except ValueError:
            print("  ERROR! Enter integer number(s), 'all', or press Enter to quit.")
            continue

        bad = [i for i in indices if i < 1 or i > len(solutions)]
        if bad:
            print(f"  ERROR! Out of range: {bad}. Valid: 1 – {len(solutions)}.")
            continue

        seen, chosen = set(), []
        for i in indices:
            if i not in seen:
                seen.add(i)
                chosen.append(solutions[i - 1])
        return chosen

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():

    args = argv[1:]
    if not args or '-h' in args or '--help' in args:
        usage()

    poscar_file = args[0]
    working_dir = os.getcwd()
    mono        = read_POSCAR(poscar_file)
    n_prim      = mono["total"]

    print(f"\n{'='*72}")
    print(f"  vaspTwist.py -- Commensurate twist-angle search")
    print(f"  Input file      : {poscar_file}")
    print(f"  Primitive atoms : {n_prim}")
    print(f"  Atom limit      : {MAX_ATOMS}  (both layers combined)")
    print(f"  Table filter    : strain <= {STRAIN_SHOW:.1f}%")
    print(f"{'='*72}\n")

    all_solutions = enumerate_twist_angles(mono["lattice"], n_prim)

    if not all_solutions:
        print(f"  No commensurate angles found (atom limit = {MAX_ATOMS}).")
        return

    shown  = [s for s in all_solutions if s["strain_pct"] <= STRAIN_SHOW]
    hidden = len(all_solutions) - len(shown)

    print(f"  Found {len(all_solutions)} solution(s) total; "
          f"showing {len(shown)} with strain <= {STRAIN_SHOW:.1f}%"
          + (f"  ({hidden} hidden, edit STRAIN_SHOW to see more)" if hidden else "")
          + ":\n")

    if not shown:
        print(f"  No solutions pass the strain filter.")
        print(f"  Edit STRAIN_SHOW at the top of the script to see more.")
        return

    print_table(shown)
    chosen = prompt_selection(shown)

    if not chosen:
        print("\n  Nothing selected. Exiting.\n")
        return

    # Ask about z-flip once, applies to all chosen angles
    flip = False
    thickness = (np.max(mono["pos_cart"][:, 2]) -
                 np.min(mono["pos_cart"][:, 2]))
    if thickness > 1e-8:
        while True:
            ans = input("\n  Flip top layer in z (Y/N): ").strip().upper()
            if ans and ans[0] == 'Y':
                flip = True;  break
            if ans and ans[0] == 'N':
                break
            print("  ERROR! Enter Y or N.")

    print()
    written = 0
    for sol in chosen:
        tag  = f"twist_{sol['angle_deg']:.4f}deg_m{sol['m']}_n{sol['n']}"
        odir = os.path.join(working_dir, tag)
        os.makedirs(odir, exist_ok=True)
        try:
            data   = build_twist_poscar(mono, sol, flip=flip)
            labels = make_labels(data["elements"], data["counts"])
            write_POSCAR(os.path.join(odir, "POSCAR"),
                         data["lattice"],
                         data["elements"],
                         data["counts"],
                         data["pos_direct"],
                         data["sel_dyn"],
                         data["flags"],
                         labels)
            total = sum(data["counts"])
            print(f"  Written : {tag}/POSCAR  "
                  f"({total} atoms, strain = {sol['strain_pct']:.4f}%)")
            written += 1
        except Exception as e:
            print(f"  WARNING : could not build {tag} -- {e}")

    print(f"\n  Done -- {written} POSCAR(s) written.\n")


if __name__ == "__main__":
    main()
